### ISSUE TITLE
JWK private key

### ISSUE THREAD

**Issue by ucontacti** [smallstep/clients#1]
I have been using your code as a reference and I tried to use it but every time I get this error:
```
The request lacked necessary authorization to be completed. Please see the certificate authority logs for more info.
```
And on the server side it says:
```
authority.Authorize: authority.authorizeSign: authority.authorizeToken: provisioner not found or invalid audience (https://***:8277/1.0/sign)
```
I did not change the audience part of the jwt_body
One another thing that made me wonder was in your nodejs code I saw this:
https://github.com/smallstep/clients/blob/a175a9cd3072859d4d3053b34a7596b746e4f8a8/node/signer.js#L111
I don't quite understand why the sender (client) needs the CA's private key JWK.

**Comment by tashian** [comment]
Hi!

The client needs the JWK in order to authenticate its request with the CA.
The client uses the JWK to sign a base64-encoded one-time-use CA authentication token (which is a JWT).
This is just one way of authenticating a certificate request with the CA—using the JWK provisioner.

The `step` client also does this for `step ca token` or `step ca certificate` commands, when using a JWK provisioner.
The difference is that, for usability, `step` reads an encrypted JWK from the `/provisioners` endpoint of the CA, and then asks you for the JWK password in order to decrypt it in memory and then sign the CA authentication token.

**Comment by tashian** [comment]
I've updated the main README for this repo with a "you will need section" that describes how to get and decrypt the JWK.

**Comment by ucontacti** [comment]
Amazing, thanks for the help.
Just one thing about "You will need" part of README, I don't see the decrypt subcommand in "step crypto jwk".
https://smallstep.com/docs/step-cli/reference/crypto/jwk#commands

**Comment by ucontacti** [comment]
I think you meant jwe in the cli than jwk

**Comment by tashian** [comment]
good catch, thank you!
